### ISSUE TITLE
Conflict with sibling_spacing and Incremental Reading

### ISSUE THREAD

**Issue by aleksejrs** [lovac42/AddonManager21#2]
When starting Anki Version 2.0.52 Qt 4.8.1 PyQt 4.9.1 with AddonManager21 (Backported) Updated 2018-12-24:

```
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt/main.py", line 165, in onOpenProfile
  File "aqt/main.py", line 244, in loadProfile
  File "anki/hooks.py", line 26, in runHook
  File "/home/fc/.local/share/Anki2/addons/sibling_spacing.py", line 103, in profileLoaded
    mw.addonManager.rebuildAddonsMenu()
  File "anki/hooks.py", line 55, in repl
  File "aqt/addons.py", line 55, in rebuildAddonsMenu
AttributeError: 'AddonManager21' object has no attribute '_menus'
```

When opening or closing the review screen:

```
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt/webview.py", line 157, in _loadFinished
  File "aqt/reviewer.py", line 182, in <lambda>
  File "aqt/reviewer.py", line 221, in _showQuestion
  File "anki/hooks.py", line 26, in runHook
  File "/home/fc/.local/share/Anki2/addons/ir/main.py", line 92, in restoreView
    if viewingIrText():
  File "/home/fc/.local/share/Anki2/addons/ir/util.py", line 24, in viewingIrText
    if (isIrCard(mw.reviewer.card) and
  File "/home/fc/.local/share/Anki2/addons/ir/util.py", line 17, in isIrCard
    mw.readingManager.settings['modelName'])):
AttributeError: ReadingManager instance has no attribute 'settings'
```

**Comment by lovac42** [comment]
Thanks for reporting, replace the main.py file with this one should fix it.
https://raw.githubusercontent.com/lovac42/AddonManager21/master/src/addonman21/main.py

**Comment by aleksejrs** [comment]
Thanks, it works.
